### ISSUE TITLE
Wallpapers

### ISSUE THREAD

**Issue by neel-desh** [madhur/dotfiles#1]
Hello Madhur,

can you please share the wallpapers you've mentioned in the screenshots?

Ps: loved that setup.

**Comment by madhur** [comment]
Thanks, you can find it in this repo https://github.com/madhur/wallpapers

Ping me if you are not able to find the ones you are looking for.

**Comment by neel-desh** [comment]
Thanks dude! 

Ps: I saw your commit like 50 mins ago 😂 . I was like ye hota hai developer Ajj bhi apne machine ko customize karne betha hai.

Ps PS: I'm also doing the same. Trying to setup my machine the same as yours.

**Comment by madhur** [comment]
Haha. Not really customize. There is a file backup.sh in the repo which I
run every weekend.

It automatically backs up any changes in dotfiles and commits it to this
repo.
